# Generated by Django 5.1.6 on 2025-03-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="time",
            field=models.CharField(blank=True, default="12 March 2025", max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.CharField(blank=True, default="12 March 2025", max_length=100),
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/posts"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="myapp.post",
                    ),
                ),
            ],
        ),
    ]
